---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: 'enhancement'
assignees: ''
body:
  - type: textarea
      id: currentproblem
      attributes:
        label: Describe the current problem or need
        description: Do you have any ideas for improvements, or do you have a current issue that could be improved?
      validations:
        required: true
  - type: textarea
      id: soulution1
      attributes:
        label: Describe the solution you would like
        description: ""
      validations:
        required: true
  - type: textarea
      id: AnotherSolution
      attributes:
        label: Do you have another solution?
        description: ""
